horta/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('hortadb/', include('hortadb.urls')),
    path('admin/', admin.site.urls),
]

hortadb/urls.py
from django.urls import path
from . import views

app_name = 'hortadb'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),

    # SPECIES

    path('species/', views.SpeciesView.as_view(), name='species'),
    path('species/<int:sid>/', views.detail, name='detail'),
    path('species/new/', views.species_new, name='species_new'),
    #path('species/', views.species, name='species'),
    #path('species/<int:pk>/', views.DetailView.as_view(), name='detail'),

    # CULTIVARS

    path('cultivar/<int:cid>/', views.cultivar, name='cultivar'),

    # RESOURCES

    path('resources', views.resources, name='resources'),

    # tiago

    path('tiago/', views.tiago, name='tiago'),

]

hortadb/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

class Species(models.Model):
    common_name = models.CharField(max_length=100)
    species     = models.CharField(max_length=100)
    subspecies  = models.CharField(max_length=50, blank=True)
    genus       = models.CharField(max_length=100)
    family      = models.CharField(max_length=100)
    order       = models.CharField(max_length=100)

    def __str__(self):
        return self.common_name

    def binomial_name(self):
        if not self.subspecies:
            return '{} {}'.format(self.genus, self.species[3:])
        else:
            return '{} {} {}'.format(self.genus, self.species[3:], self.subspecies)

    class Meta:
        verbose_name_plural = "species"


class Cultivar(models.Model):
    LIFE_CYCLE_CHOICES = (
        ('AN', 'annual'),
        ('BI', 'biennial'),
        ('PR', 'perennial'),
        ('UN', 'unknown'),
    )
    species    = models.ForeignKey(Species, on_delete=models.CASCADE)
    variety    = models.CharField(max_length=100)
    life_cycle = models.CharField(
                        choices    = LIFE_CYCLE_CHOICES,
                        max_length = 20,
                        default    = 'UN',
                        blank      = False,
    )

    def __str__(self):
        return '%s %s' % (self.species, self.variety)

    def get_name(self):
        """
        Returns the common name of the cultivar.
        """
        return self.species.common_name
    get_name.short_description = ('common name')
    get_name.admin_order_field = ('species__common_name')

    def get_species(self):
        """
        Returns the species of the cultivar.
        """
        return self.species.species
    get_species.short_description = ('plant species')
    get_species.admin_order_field = ('species__species')


class Seed(models.Model):
    plant_seed   = models.ForeignKey(Cultivar, on_delete=models.CASCADE)
    brand        = models.CharField('brand/origin', max_length=50)
    date_sowo_ini = models.IntegerField(
                        'month sowing outside starts',
                        blank=True, null= True,
                        validators=[MinValueValidator(1), MaxValueValidator(12)])
    date_sowo_end = models.IntegerField(
                        'month sowing outside ends',
                        blank=True, null= True,
                        validators=[MinValueValidator(1), MaxValueValidator(12)])
    date_sowi_ini = models.IntegerField(
                        'month sowing inside starts',
                        blank=True, null= True,
                        validators=[MinValueValidator(1), MaxValueValidator(12)])
    date_sowi_end = models.IntegerField(
                        'month sowing inside ends',
                        blank=True, null= True,
                        validators=[MinValueValidator(1), MaxValueValidator(12)])
    date_tran_ini = models.IntegerField(
                        'month transplanting starts',
                        blank=True, null= True,
                        validators=[MinValueValidator(1), MaxValueValidator(12)])
    date_tran_end = models.IntegerField(
                        'month transplanting ends',
                        blank=True, null= True,
                        validators=[MinValueValidator(1), MaxValueValidator(12)])
    date_harv_ini = models.IntegerField(
                        'month harvesting starts',
                        blank=True, null= True,
                        validators=[MinValueValidator(1), MaxValueValidator(12)])
    date_harv_end = models.IntegerField(
                        'month harvesting ends',
                        blank=True, null= True,
                        validators=[MinValueValidator(1), MaxValueValidator(12)])

    days_to_maturity = models.IntegerField('days to maturity', blank=True, null=True)
    fruit_size       = models.FloatField('average size of fruit [cm]', blank=True, null=True)
    fruit_weight     = models.FloatField('average weight of fruit [cm]', blank=True, null=True)
    plant_spacing    = models.FloatField('average space between plants [cm]', blank=True, null=True)
    row_spacing      = models.FloatField('average space between rows [cm]', blank=True, null=True)
    germination_temp = models.FloatField('average weight of fruit [cm]', blank=True, null=True)


    def __str__(self):
        return '%s %s' % (self.plant_seed, self.brand)


class Seed_Packet(models.Model):
    seed_packet   = models.ForeignKey(Seed, on_delete=models.CASCADE)
    date_packing  = models.DateField('packing date of seed bag', blank=True, null=True)
    date_validity = models.DateField('expiry date of seed bag', blank=True, null=True)
    weight        = models.IntegerField('weight of seed bag [g]', blank=True, null=True)
    #organic      = models.BooleanField('are the seeds organic?')
    #price        = models.FloatField('price per bag', blank=True, null=True)

    def __str__(self):
        return '%s' % (self.seed_packet)

    class Meta:
        verbose_name = "seed packet"
        verbose_name_plural = "seed packets"


class Playlist(models.Model):
    channel_name      = models.CharField(max_length=50)
    playlist_name     = models.CharField(max_length=100)
    playlist_link     = models.URLField()
    short_description = models.TextField(max_length=600, blank=True)
    created_at        = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s %s' % (self.channel_name, self.playlist_name)

hortadb/forms.py
from django import forms

from .models import Species

class SpeciesForm(forms.Form):

    species = forms.CharField(
        help_text = 'Enter the species.',
        max_length = 100,
    )

hortadb/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django_tables2 import RequestConfig

from .models import Species, Cultivar, Seed, Seed_Packet, Playlist
from .forms import SpeciesForm
from .tables import SpeciesTable

import locale
# this reads the environment and inits the right locale
locale.setlocale(locale.LC_ALL, "")


class IndexView(generic.ListView):
    template_name = 'hortadb/index.html'
    context_object_name = 'species_list'

    def get_queryset(self):
        return Species.objects.order_by('family')

# SPECIES

class SpeciesView(generic.ListView):
    template_name = 'hortadb/base_species.html'
    context_object_name = 'species_list'

    def get_queryset(self):
        return sorted(Species.objects.all(), key=lambda s: locale.strxfrm(s.common_name))


class DetailView(generic.DetailView):
    model = Species, Cultivar, Seed
    template_name = 'hortadb/detail.html'

    def get_queryset(self):
        """
        Excludes any species that aren't published yet.
        """
        return Species.objects.all()

def detail(request, sid):
    return render(request, 'hortadb/detail.html', {
        'species': Species.objects.get(pk=sid),
        'months':  list(range(1,13)),
    })

def species_new(request):
    form = SpeciesForm()
    return render(request, 'hortadb/species_edit.html', {
        'form': form})

#def species(request):
#    table = SpeciesTable(Species.objects.all())
#    RequestConfig(request).configure(table)
#    return render(request, 'hortadb/base_species.html', {
#        'table': table,
#    })


# CULTIVARS

def cultivar(request, cid):
    return render(request, 'hortadb/cultivar.html', {
        'cultivar': Cultivar.objects.get(pk=cid),
        'months':   list(range(1,13)),
    })


# RESOURCES

def resources(request):
    return render(request, 'hortadb/base_resources.html', {
        'playlists': Playlist.objects.order_by('-created_at')[:3]
    })



# tiago

def tiago(request):
    return render(request, 'tiago.html', {
        'species': Species.objects.all()
    })

hortadb/templates/hortadb/base.html
{% load static %}

<!doctype html>
<html>

<head>
    <title>{{ title }} - {% block title %}Untitled{% endblock %}</title>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <!-- icons -->
    <link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
        crossorigin="anonymous">

    <!-- project stylesheets -->
    <link rel="stylesheet" href="{% static 'hortadb/style.css' %}">

   <!-- tables ?? -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

</head>

<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">hortaDB</a>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        {% block button %} {% endblock %}
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">Sign out</a>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        {% for nav in navigation %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ nav.url }}">
                                <i class="fas fa-{{ nav.icon }}"></i>
                                {{ nav.title }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
                {% block content %}No content.{% endblock %}
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

hortadb/templates/hortadb/base_resources.html
{% extends 'hortadb/base.html' %}

{% block title %}Resources{% endblock title%}

{% block content %}

    {% if playlists %}
    <h2>Listas de reprodução</h2>
    <div class="row">
        {% include "hortadb/resources_card.html" %}
    </div>
    {% else %}
        <p>No playlists are available.</p>
    {% endif %}


{% endblock content %}

hortadb/templates/hortadb/base_species.html
{% extends 'hortadb/base.html' %}
{# % load render_table from django_tables2 % #}

{% block button %}
    <a class="btn btn-primary" href="{% url 'hortadb:species_new' %}" role="button">Add species</a>
{% endblock %}

{% block title %}
    Species
{% endblock title %}

{% block content %}
    <!-- render_table table -->

    {% if species_list %}
        <table class="table">
            <tr>
                <th>Common name</th>
                <th>Binomial name</th>
                <th>Order</th>
                <th>Family</th>
                <th>Genus</th>
                <th>Number of varieties</th>
            </tr>

            {% for s in species_list %}
            <tr>
                <td><a href="{% url 'hortadb:detail' s.id %}">{{ s.common_name }}</a></td>
                <td>{{ s.binomial_name }}</td>
                <td>{{ s.order }}</td>
                <td>{{ s.family }}</td>
                <td>{{ s.genus }}</td>
                <td>{{ s.cultivar_set.all.count }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No species are available.</p>
    {% endif %}

</div>


{% endblock %}

hortadb/templates/hortadb/calendar-line.html
{% spaceless %}
{% if start_date != null and end_date %}
    <tr class="{{ class }}">
    {% for i in months %}
        <td>
            {% if i >= start_date and i <= end_date %}
            <span class="check"></span>
            {% endif %}
        </td>
    {% endfor %}
    </tr>
{% endif %}
{% endspaceless %}

hortadb/templates/hortadb/calendar.html
<table class="seed-calendar">
    <thead>
        <tr>
        {% for i in months %}
            <th>{{ i }}</th>
        {% endfor %}
        </tr>
    </thead>

    <tbody>
        {% include "hortadb/calendar-line.html" with class="seed-calendar-sowi" start_date=seed.date_sowi_ini end_date=seed.date_sowi_end %}
        {% include "hortadb/calendar-line.html" with class="seed-calendar-sowo" start_date=seed.date_sowo_ini end_date=seed.date_sowo_end %}
        {% include "hortadb/calendar-line.html" with class="seed-calendar-tran" start_date=seed.date_tran_ini end_date=seed.date_tran_end %}
        {% include "hortadb/calendar-line.html" with class="seed-calendar-harv" start_date=seed.date_harv_ini end_date=seed.date_harv_end %}
    </tbody>
</table>

hortadb/templates/hortadb/cultivar.html
{% extends 'hortadb/base.html' %} {% load static %}

{% block title %}
    Cultivar: {{ cultivar.species }}
{% endblock %}

{% block content %}
<h1>{{ cultivar.species }} {{ cultivar.variety }}</h1>

<div class="row">
    {% if cultivar.seed_set %}
    <table class="table table-bordered">
        
        <thead>
            <tr>
                <th>Origin</th>
                <th>Days to maturity</th> 
                <th>Fruit size [cm]</th>
                <th>Fruit weight [g]</th>
                <th>Plant spacing [cm]</th>
                <th>Row spacing [cm]</th>
                <th>Calendar</th>
            </tr>
        </thead>
        
        <tbody>
            {% for seed in cultivar.seed_set.all %}
            <tr>
                <td>{{ seed.brand }}</td>
                <td>{{ seed.days_to_maturity }}</td>
                <td>{{ seed.fruit_size }}</td>
                <td>{{ seed.fruit_weight }}</td>
                <td>{{ seed.plant_spacing }}</td>
                <td>{{ seed.row_spacing }}</td>
                <td style="width: 1%">
                    {% include "hortadb/calendar.html" with seed=seed %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %} No content {% endif %}
</div>
{% endblock %}

hortadb/templates/hortadb/detail.html
{% extends 'hortadb/base.html' %} {% load static %}

{% block title %}
    Species: {{ species.common_name }}
{% endblock %}

{% block content %}
<h1>{{ species.common_name }} </h1>
<hr>

<div class="row">
    <div class="col-9">
        <p>{% lorem %}</p>
        <p>{% lorem %}</p>
        <p>{% lorem %}</p>
    </div>

    <div class="col-3">
        <div class="card text-center mb-3">
            <h5 class="card-header"><i><strong>{{ species.species }}</i></strong></h5>
            <div class="card-body">
                <h5 class="card-title">{{ species.common_name }}</h5>
                <p class="card-text">Genus: {{ species.genus }} </p>
                <p class="card-text">Family: {{ species.family }}</p>
                <p class="card-text">Order: {{ species.order }}</p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    {% if species.cultivar_set %}
    <table class="table table-bordered">
        <tr>
            <th>Common name</th>
            <th>Life cycle</th>
            <th>Calendar</th>
            <th>Review</th>
        </tr>
        {% for c in species.cultivar_set.all %}
        <tr>
            <td><a href="{% url 'hortadb:cultivar' c.id %}">{{ c.variety }}</a></td>
            <td>{{ c.get_life_cycle_display }}</td>
            <td style="width: 1%">
            {% with seed=c.seed_set.first %}
                {% include "hortadb/calendar.html" with seed=seed %}
            {% endwith %}
            </td>
            <td>Review</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
        <p>No species are available.</p>
    {% endif %}
</div>
{% endblock %}

hortadb/templates/hortadb/index.html
{% extends 'hortadb/base.html' %} {% load static %}

{% if species_list %}
    <ul>
    {% for species in species_list %}
        <li><a href="{% url 'hortadb:detail' species.id %}">{{ species.common_name }}</a></li>
    {% endfor %}    
    </ul>
{% else %}
    <p>No species are available.</p>
{% endif %}

hortadb/templates/hortadb/resources_box.html
{% if playlist %}

<div class="col">
    <div class="video-container">
        <iframe id="ytplayer" type="text/html" src="{{ playlist.playlist_link }}" frameborder="0" allowfullscreen></iframe>
    </div>
    <h5>{{ playlist.short_description }}</h5>
</div>

{% endif %}

hortadb/templates/hortadb/resources_card.html
{% block content %}

    {% if playlists %}
        {% for p in playlists %}
            {% include "hortadb/resources_box.html" with playlist=p %}
        {% endfor %}
        <div class="col">
            <a class="btn btn-primary" href="hortadb/resources-playlist-all.html" role="button">Link</a>
        </div>
    {% else %}
        No playlists.
    {% endif %}


{% endblock content %}

hortadb/templates/hortadb/species.html
{% extends 'hortadb/base.html' %}

{% block button %}
    <a class="btn btn-primary" href="{% url 'hortadb:species_new' %}" role="button">Add species</a>
{% endblock %}

{% block content %}
    {% if species_list %}
        <table class="table">
            <tr>
                <th>Common name</th>
                <th>Species</th>
                <th>Genus</th>
                <th>Family</th>
                <th>Order</th>
            </tr>

            {% for s in species_list %}
            <tr>
                <td><a href="{% url 'hortadb:detail' s.id %}">{{ s.common_name }}</a></td>
                <td>{{ s.species }}</td>
                <td>{{ s.genus }}</td>
                <td>{{ s.family }}</td>
                <td>{{ s.order }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No species are available.</p>
    {% endif %}
{% endblock %}

hortadb/templates/hortadb/species_edit.html
{% extends 'hortadb/base.html' %} {% load static %}

{% block content %}
    <h1>New species</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}